/* global client */
/* eslint-env mocha */
const chai = require('chai')
chai.should()
const testCaseFactory = require('./test-case-factory')

describe('CLI', () => {
  it('should handle test groups', () => {
    return testCaseFactory
      .create('test-group-test')
      .group('positive')
      .feature('positive addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .group('negative')
      .feature('negative addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run()
      .then((result) => {
        result.features[0].result.status.should.be.passed
        result.features[0].result.scenarioCounts.should.deep.equal({passed: 2})
        result.features[0].scenarios[0].result.status.should.be.passed
        result.features[0].scenarios[0].result.stepCounts.should.deep.equal({passed: 5})
        result.features[0].scenarios[1].result.status.should.be.passed
        result.features[0].scenarios[1].result.stepCounts.should.deep.equal({passed: 5})
        result.features[1].result.status.should.be.passed
        result.features[1].result.scenarioCounts.should.deep.equal({passed: 2})
        result.features[1].scenarios[0].result.status.should.be.passed
        result.features[1].scenarios[0].result.stepCounts.should.deep.equal({passed: 5})
        result.features[1].scenarios[1].result.status.should.be.passed
        result.features[1].scenarios[1].result.stepCounts.should.deep.equal({passed: 5})
      })
  })

  it('should handle test group filtering', () => {
    return testCaseFactory
      .create('test-group-filtering-test')
      .group('positive')
      .feature('positive addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .group('negative')
      .feature('negative addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--group', 'negative'])
      .then((result) => {
        result.features.length.should.equal(1)
        result.features[0].name.should.equal('negative addition')
        result.features[0].result.status.should.be.passed
      })
  })

  it('should handle test group skipping', () => {
    return testCaseFactory
      .create('test-group-skipping-test')
      .group('positive')
      .feature('positive addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .group('negative')
      .feature('negative addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--skipgroup', 'positive'])
      .then((result) => {
        result.features.length.should.equal(1)
        result.features[0].name.should.equal('negative addition')
        result.features[0].result.status.should.be.passed
      })
  })

  it('should handle feature tag filtering', () => {
    return testCaseFactory
      .create('feature-tag-filtering-test')
      .feature('positive addition', ['positive', 'addition'])
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative addition', ['negative', 'addition'])
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--tag', 'negative'])
      .then((result) => {
        result.features.length.should.equal(1)
        result.features[0].result.scenarioCounts.should.deep.equal({passed: 2})
        result.features[0].name.should.equal('negative addition')
      })
  })

  it('should handle feature tag skipping', () => {
    return testCaseFactory
      .create('feature-tag-skipping-test')
      .feature('positive addition', ['positive', 'addition'])
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative addition', ['negative', 'addition'])
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--skiptags', 'positive'])
      .then((result) => {
        result.features.length.should.equal(1)
        result.features[0].result.scenarioCounts.should.deep.equal({passed: 2})
        result.features[0].name.should.equal('negative addition')
      })
  })

  it('should handle scenario tag filtering', () => {
    return testCaseFactory
      .create('scenario-tag-filtering-test')
      .feature('positive addition')
      .scenario('small numbers', ['small', 'numbers'])
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers', ['big', 'numbers'])
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .run(['--tag', 'big'])
      .then((result) => {
        result.features[0].scenarios.length.should.equal(1)
        result.features[0].scenarios[0].name.should.equal('big numbers')
        result.features[0].scenarios[0].result.status.should.be.passed
      })
  })

  it('should handle scenario tag skipping', () => {
    return testCaseFactory
      .create('scenario-tag-skipping-test')
      .feature('positive addition')
      .scenario('small numbers', ['small', 'numbers'])
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers', ['big', 'numbers'])
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .run(['--skiptags', 'small'])
      .then((result) => {
        result.features[0].scenarios.length.should.equal(1)
        result.features[0].scenarios[0].name.should.equal('big numbers')
        result.features[0].scenarios[0].result.status.should.be.passed
      })
  })

  it('should handle multiple scenario tag filtering', () => {
    return testCaseFactory
      .create('multipleFeatureTagSkippingTest')
      .feature('positive addition', ['positive', 'addition'])
      .scenario('small numbers', ['smallPositiveNumbers'])
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers', ['bigPositiveNumbers'])
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative addition', ['negative', 'addition'])
      .scenario('small numbers', ['smallNegativeNumbers'])
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers', ['bigNegativeNumbers'])
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--tag', 'smallPositiveNumbers', '--tag', 'bigNegativeNumbers'])
      .then((result) => {
        result.features[0].scenarios[0].name.should.equal('big numbers')
        result.features[1].scenarios[0].name.should.equal('small numbers')
      })
  })

  it('should handle multiple scenario tag skipping', () => {
    return testCaseFactory
      .create('multipleFeatureTagSkippingTest')
      .feature('positive addition', ['positive', 'addition'])
      .scenario('small numbers', ['smallPositiveNumbers'])
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers', ['bigPositiveNumbers'])
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative addition', ['negative', 'addition'])
      .scenario('small numbers', ['smallNegativeNumbers'])
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers', ['bigNegativeNumbers'])
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--skiptags', 'smallPositiveNumbers,bigNegativeNumbers'])
      .then((result) => {
        result.features[0].scenarios[0].name.should.equal('small numbers')
        result.features[1].scenarios[0].name.should.equal('big numbers')
      })
  })

  it('should handle multiple scenario tag filtering and skipping', () => {
    return testCaseFactory
      .create('multipleFeatureTagFilteringAndSkippingTest')
      .feature('positive addition')
      .scenario('small numbers', ['smallPositiveNumbers', 'positive', 'addition'])
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers', ['bigPositiveNumbers', 'positive', 'addition'])
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative addition', ['negative', 'addition'])
      .scenario('small numbers', ['smallNegativeNumbers'])
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers', ['bigNegativeNumbers'])
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--tag', 'positive', '--tag', 'negative', '--skiptags', 'smallPositiveNumbers,bigNegativeNumbers'])
      .then((result) => {
        result.features[0].scenarios[0].name.should.equal('small numbers')
        result.features[1].scenarios[0].name.should.equal('big numbers')
      })
  })

  it('should handle specified features execution', () => {
    return testCaseFactory
      .create('specified-features-execution-test')
      .feature('positive-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--test', 'features/negative-addition'])
      .then((result) => {
        result.features.length.should.equal(1)
        result.features[0].name.should.equal('negative-addition')
        result.features[0].result.status.should.be.passed
      })
  })

  it('should handle single feature execution', () => {
    return testCaseFactory
      .create('single-feature-execution-test')
      .feature('positive-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['features/negative-addition'])
      .then((result) => {
        result.features.length.should.equal(1)
        result.features[0].name.should.equal('negative-addition')
        result.features[0].result.status.should.be.passed
      })
  })

  it('should handle single scenario execution', () => {
    return testCaseFactory
      .create('single-scenario-execution-test')
      .feature('positive-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['features/negative-addition:11'])
      .then((result) => {
        result.features.length.should.equal(1)
        result.features[0].name.should.equal('negative-addition')
        result.features[0].result.status.should.be.passed
        result.features[0].scenarios.length.should.equal(1)
        result.features[0].scenarios[0].name.should.equal('big numbers')
        result.features[0].scenarios[0].result.status.should.be.passed
      })
  })

  it('should handle multiple feature execution', () => {
    return testCaseFactory
      .create('multiple-feature-execution-test')
      .feature('positive-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .feature('complex-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4i in A field', () => client.setValue('#a', '4i'))
      .and('User enter 5i in B field', () => client.setValue('#b', '5i'))
      .when('User press Add button')
      .then('The result should contain 9i', () => client.assert.containsText('#result', '9i'))
      .run(['features/negative-addition', 'features/positive-addition'])
      .then((result) => {
        result.features.length.should.equal(2)
        result.features[0].name.should.equal('negative-addition')
        result.features[0].result.status.should.be.passed
        result.features[1].name.should.equal('positive-addition')
        result.features[1].result.status.should.be.passed
      })
  })

  it('should handle single feature and feature folder execution', () => {
    return testCaseFactory
      .create('single-feature-and-feature-folder-execution-test')
      .feature('positive-small-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .feature('positive-big-addition')
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .group('negative')
      .feature('negative-small-addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .group('negative')
      .feature('negative-big-addition')
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['features/positive-small-addition', 'features/negative'])
      .then((result) => {
        result.features.length.should.equal(3)
        result.features[0].name.should.equal('positive-small-addition')
        result.features[0].result.status.should.be.passed
        result.features[1].name.should.equal('negative-big-addition')
        result.features[1].result.status.should.be.passed
        result.features[2].name.should.equal('negative-small-addition')
        result.features[2].result.status.should.be.passed
      })
  })

  it('should return zero exit code on success', () => {
    return testCaseFactory
      .create('zero-exit-code-test')
      .feature('addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .run()
      .then((result) => {
        result.exitCode.should.equal(0)
      })
  })

  it('should return non zero exit code on failure', () => {
    return testCaseFactory
      .create('non-zero-exit-code-test')
      .feature('addition')
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 8', () => client.assert.containsText('#result', 8))
      .run()
      .then((result) => {
        result.exitCode.should.not.equal(0)
      })
  })

  it('should handle multiple environments and tag filtering', () => {
    return testCaseFactory
      .create('multi-environment-and-tags-test')
      .feature('positive addition')
      .scenario('small numbers', ['small', 'numbers'])
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers', ['big', 'numbers'])
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .run(['--env', 'default,default', '--tag', 'big'])
      .then((result) => {
        result.features[0].scenarios.length.should.equal(1)
        result.features[0].scenarios[0].name.should.equal('big numbers')
        result.features[0].scenarios[0].result.status.should.be.passed
      })
  })

  it('should handle paralell execution and tag filtering', () => {
    return testCaseFactory
      .create('paralell-tag-filtering-test', { paralell: true })
      .feature('positive addition', ['positive', 'addition'])
      .scenario('small numbers')
      .given('User is on the simple calculator page', () => client.init())
      .and('User enter 4 in A field', () => client.setValue('#a', 4))
      .and('User enter 5 in B field', () => client.setValue('#b', 5))
      .when('User press Add button', () => client.click('#add'))
      .then('The result should contain 9', () => client.assert.containsText('#result', 9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter 4 in A field')
      .and('User enter 5 in B field')
      .when('User press Add button')
      .then('The result should contain 9')
      .feature('negative addition', ['negative', 'addition'])
      .scenario('small numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field', () => client.setValue('#a', -4))
      .and('User enter -5 in B field', () => client.setValue('#b', -5))
      .when('User press Add button')
      .then('The result should contain -9', () => client.assert.containsText('#result', -9))
      .scenario('big numbers')
      .given('User is on the simple calculator page')
      .and('User enter -4 in A field')
      .and('User enter -5 in B field')
      .when('User press Add button')
      .then('The result should contain -9')
      .run(['--tag', 'negative'])
      .then((result) => {
        result.features.length.should.equal(1)
        result.features[0].result.scenarioCounts.should.deep.equal({passed: 2})
        result.features[0].name.should.equal('negative addition')
      })
  })
})
